from fastapi import Response
from pandas import DataFrame
from starlette import status

from automind_api.app.models.applier import ApplierGenerateNewDatasetParameter
from automind_api.app.models.i3s import ObjectInfo
from automind_api.app.models.view_sp import AvailableSP, ViewMetaData
from automind_api.app.repositories.dataset import dataset_to_mindsdb
from automind_api.app.repositories.i3s import exec_mutation_sp
from automind_api.app.services.file import generate_dataframe_info_by_ref


def generate_409_conflict_response(res: Response):
    res.status_code = status.HTTP_409_CONFLICT
    return {
        "state": 2,
        "message": "dataset is not found or target column not be specified or llm response not exists",
    }


def generate_new_dataset_from_df(
    df: DataFrame,
    dataset_id: int,
    user_id: int,
    object_info: ObjectInfo,
    prefix: str,
    metadata_view: ViewMetaData,
):
    df_info = generate_dataframe_info_by_ref(df)

    applier_generate_new_dataset_opt: ApplierGenerateNewDatasetParameter = {
        "name": f"{prefix}_preprocessed_" + object_info.get("CName"),
        "des": f"this dataset is generated by {metadata_view.get('metadata_id', '')} for {prefix}",
        "origin_dataset_id": dataset_id,
        "user_id": user_id,
        **df_info,
    }

    dataset_to_mindsdb(df, df_info["md5"])

    update_metadata_status_opt = {
        "dataset_id": dataset_id,
        "user_id": user_id,
        "status": metadata_view.get("status"),
        "applier_status": "complete",
    }

    exec_mutation_sp(
        AvailableSP.update_metadata_status, update_metadata_status_opt
    )

    exec_mutation_sp(
        AvailableSP.applier_generate_new_dataset,
        applier_generate_new_dataset_opt,
    )
