[project]
name = "automind"
version = "0.1.0"
description = "an automl framework with llm-based data processing module"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  # -------------------- model --------------------
  "xgboost",
  "openai",
  "tpot==0.12.2",
  "scikit-learn==1.6.1",


  # -------------------- data processing --------------------
  "pydantic",
  "lorem",
  "imbalanced-learn",
  "umap-learn",
  "pandas",
  "numpy",
  "scipy",
  "featuretools[dask]",
  "featuretools[premium]",
  "tiktoken",


  # issue solution: https://github.com/huggingface/datasets/issues/7693#issuecomment-3103380232
  "datasets==3.6.0",

  # -------------------- api --------------------
  "fastapi",
  "aiohttp",


  # -------------------- type stubs --------------------
  "pandas-stubs",
  "scipy-stubs",
  "microsoft-python-type-stubs@git+https://github.com/microsoft/python-type-stubs.git",

  # -------------------- visualization --------------------
  "matplotlib",
  "seaborn",

  # -------------------- testing --------------------
  "pytest",
  "psutil",
  "debugpy",

  # -------------------- util --------------------
  "setuptools",
  "wheel",
  "python-dotenv",
  "wcwidth",
  "rich",
  "graphviz",
  "pdm",
]

# also self install automind
[build-system]
requires = ["setuptools"]

[tool.pdm.scripts]
test = "uv run -m pytest ./src/automind/tests -x"
report = "uv run ./src/automind/_experiment/report.py"
report_df = "uv run ./src/automind/_experiment/report_df.py"
tpot_train = "uv run ./src/automind/_experiment/tpot_train.py"
tpot_test = "uv run ./src/automind/_experiment/tpot_test.py"
expe = "uv run ./src/automind/_experiment/main.py"

# more setting refer to: https://microsoft.github.io/pyright/#/configuration?id=sample-pyprojecttoml-file
[tool.pyright]
include = ["src"]
reportMissingTypeStubs = false
useLibraryCodeForTypes = false
extraPaths = ["typings"]
typeCheckingMode = "standard"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
ignore = ["F403", "E402"]
exclude = ["**/__init__.py"]

# define package entry
[tool.setuptools.packages.find]
where = ["src"]
