[project]
name = "automind"
version = "0.1.0"
description = "an automl framework with llm-based data processing module"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [

  # -------------------- model --------------------
  # "torch==2.6.0",
  # "optuna>=4.2.1",
  # "chainlit>=2.5.5",
  # "mcp[cli]>=1.6.0",
  "ollama",


  # -------------------- data processing --------------------
  "pydantic",
  "lorem",
  "scikit-learn",
  "imbalanced-learn",
  "umap-learn",
  "pandas",
  "numpy",
  "scipy",
  "featuretools[dask]",
  "featuretools[premium]",


  # issue solution: https://github.com/huggingface/datasets/issues/7693#issuecomment-3103380232
  "datasets==3.6.0",

  # -------------------- api --------------------
  "fastapi",
  "aiohttp",


  # -------------------- type stubs --------------------
  "pandas-stubs",
  "scipy-stubs",
  "microsoft-python-type-stubs@git+https://github.com/microsoft/python-type-stubs.git",

  # -------------------- visualization --------------------
  "matplotlib",
  "seaborn",

  # -------------------- testing --------------------
  "pytest",
  "psutil",

  # -------------------- util --------------------
  "setuptools",
  "wheel",
  "python-dotenv",
  "wcwidth",
  "rich",
  "graphviz",
]

# also self install automind
[build-system]
requires = ["setuptools"]

# define package entry
[tool.setuptools.packages.find]
where = ["src"]

# more setting refer to: https://microsoft.github.io/pyright/#/configuration?id=sample-pyprojecttoml-file
[tool.pyright]
reportMissingTypeStubs = false
useLibraryCodeForTypes = false
extraPaths = ["typings"]
# reportUnusedVariable = false
# typeCheckingMode = "basic"

[tool.ruff.lint]
ignore = ["F403", "E402"]

[tool.ruff]
line-length = 80
exclude = ["**/__init__.py"]
