[project]
name = "automind-api"
version = "0.1.0"
description = "automl service"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  # -------------------- math --------------------
  "pandas",
  "numpy",


  # -------------------- database --------------------
  "sqlalchemy",
  "mindsdb_sdk",
  "sly",

  # -------------------- console --------------------
  "wcwidth",
  "rich",
  "tqdm",

  # -------------------- driver --------------------
  "pyodbc",
  "pymysql",


  # -------------------- api --------------------
  "fastapi[standard]",
  "fastapi_utils",
  "python-multipart",
  "orjson",

  # -------------------- automind core --------------------
  "automind",

  # -------------------- type stubs --------------------
  "pandas-stubs",
  # "scipy-stubs",
  "microsoft-python-type-stubs@git+https://github.com/microsoft/python-type-stubs.git",

  # -------------------- other --------------------
  "azure-ai-language-conversations",
  "debugpy",
]


[build-system]
requires = ["setuptools"]

# define package entry
[tool.setuptools.packages.find]
where = ["src"]

# more setting refer to: https://microsoft.github.io/pyright/#/configuration?id=sample-pyprojecttoml-file
[tool.pyright]
include = ["src"]
reportMissingTypeStubs = false
useLibraryCodeForTypes = false
extraPaths = ["typings"]
disableOrganizeImports = true
# reportUnusedVariable = false
# typeCheckingMode = "basic"

[tool.ruff.lint]
ignore = ["F403", "E402"]

[tool.ruff]
line-length = 80
exclude = ["**/__init__.py"]

[tool.uv.sources]
automind = { path = "../automind/", editable = true }
